spring.application.name=owasp-mitarbeiterverwaltung
spring.datasource.url=jdbc:h2:mem:owaspdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
logging.level.root=INFO
logging.level.ch.bbw.owasp=DEBUG
server.error.include-stacktrace=never
server.error.include-message=never
